/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>

#define Memory_fault 16
#define Bus_fault 17
#define Usage_fault 18

int main(void)
{
	//enable all configuration exception

	uint32_t *pSHCSR= (uint32_t*)0xE000ED24;
	*pSHCSR |= (1 << Memory_fault);	//memory manage
	*pSHCSR |= (1 << Bus_fault);	//bus manage
	*pSHCSR |= (1 << Usage_fault);	// usage fault

	// force processor to execute some exception
	uint32_t *pSRAM = (uint32_t*)0x20010000;
	*pSRAM = 0xFFFFFFFF;

	void (*some_address) ( void );

	some_address = (void*)0x20010001;

	some_address();
    /* Loop forever */
	for(;;);
}

// implement the fault handler
void MemManage_Handler ( void )
{
	printf("Exception : MemManage\n");
	while (1);
}

void BusFault_Handler ( void )
{
	printf("Exception : BusFault_Handler\n");
	while (1);
}

void UsageFault_Handler ( void )
{
	printf("Exception : UsageFault_Handler\n");
	while (1);
}


