/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define IRQNO_TIMER2 28
#define IRQNO_I2C1 31

uint32_t *pNVIC_IPR_base = (uint32_t*)0XE000E400;
uint32_t *pNVIC_ISER_base = (uint32_t*)0XE000E100;
uint32_t *pNVIC_ISPR_base = (uint32_t*)0XE000E200;

void configure_priority_for_irq (uint8_t irq_no, uint8_t priority_value)
{
	// find out IPRx
	uint8_t iprx = irq_no / 4;
	uint32_t *ipr = pNVIC_IPR_base + iprx;

	// find position in IPRx
	uint8_t pos= (irq_no % 4) * 8;

	// configure the priority
	*ipr &= ~ (0xFF << pos);
	*ipr |= (priority_value << pos);
}



int main(void)
{
	// configure priority for the peripherals
	configure_priority_for_irq ( IRQNO_TIMER2, 0x80);
	configure_priority_for_irq ( IRQNO_I2C1, 0x70);

	// set the interrupt pending bit in the NVIC pending register
	*pNVIC_ISPR_base |= (1 << IRQNO_TIMER2);

	// enable the IRQs in the NVIC ISER
	*pNVIC_ISER_base |= (1 << IRQNO_I2C1);
	*pNVIC_ISER_base |= (1 << IRQNO_TIMER2);

    /* Loop forever */
	for(;;);
}

void TIM2_IRQHandler ( void )
{
		printf(" TIMER2 IRQ handler\n");
	// set the interrupt pending bit in the NVIC pending register
		*pNVIC_ISPR_base |= (1 << IRQNO_I2C1);
		while(1);
}

void I2C1_EV_IRQHandler ( void )
{
		printf(" I2C1 IRQ handler\n");

}
